table shtStudentMarks
	lineageTag: 2ccc517c-3212-415f-b6ba-77164bfcd849

	column 'Student Name'
		dataType: string
		lineageTag: 02600264-6a9f-4d93-8bbe-953741e900da
		summarizeBy: none
		sourceColumn: Student Name

		annotation SummarizationSetBy = Automatic

	column 'Subject Name'
		dataType: string
		lineageTag: e64e1df5-1517-47e9-b693-999707b59890
		summarizeBy: none
		sourceColumn: Subject Name

		annotation SummarizationSetBy = Automatic

	column Marks
		dataType: int64
		formatString: 0
		lineageTag: 472b43e7-7446-4a11-bcc6-1cfdf0a05134
		summarizeBy: sum
		sourceColumn: Marks

		annotation SummarizationSetBy = Automatic

	column Marks%
		dataType: double
		lineageTag: de8e2232-566b-456b-abdb-b835bc0a0038
		summarizeBy: average
		sourceColumn: Marks%

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition shtStudentMarks = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://raw.githubusercontent.com/TusharJoseph/Repo20230428/main/Power BI/POCs/poc-Git/SrcDB.xlsx"), null, true),
				    shtStudentMarks_Sheet = Source{[Item="shtStudentMarks",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(shtStudentMarks_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Student Name", type text}, {"Subject Name", type text}, {"Marks", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Marks%", each [Marks]/100),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Marks%", Percentage.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

